feat(HACBS-2222): add failOnEmptyResult parameter to apply-mapping
When set to "true", the task will fail in the case when the resulting
snapshot has 0 components.

Signed-off-by: Martin Malina <mmalina@redhat.com>

diff --git a/catalog/task/apply-mapping/0.4/apply-mapping.yaml b/catalog/task/apply-mapping/0.4/apply-mapping.yaml
--- a/catalog/task/apply-mapping/0.4/apply-mapping.yaml
+++ b/catalog/task/apply-mapping/0.4/apply-mapping.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: apply-mapping
   labels:
-    app.kubernetes.io/version: "0.3"
+    app.kubernetes.io/version: "0.4"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -19,6 +19,10 @@ spec:
       type: string
       description: The path to the config file containing the mapping
       default: ""
+    - name: failOnEmptyResult
+      type: string
+      description: Fail the task if the resulting snapshot contains 0 components
+      default: "false"
   workspaces:
     - name: config
       description: The workspace where the extra config file containing the mapping resides
@@ -65,3 +69,9 @@ spec:
           <<< "${SNAPSHOT}${CONFIG_JSON}" | tee $(results.snapshot.path)
 
         echo "true" | tee $(results.mapped.path)
+
+        if [ "$(params.failOnEmptyResult)" = "true" ] && [ $(jq '.components | length' $(results.snapshot.path)) -eq 0 ]
+        then
+          echo "ERROR: Resulting snapshot contains 0 components"
+          exit 1
+        fi
