feat(RELEASE-1734): remove binary field and add skip logic
this PR removes the requirement of the binary
field and adds the skip logic to compress the
artifact

Signed-off-by: Leandro Mendes <lmendes@redhat.com>

diff --git a/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml b/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml
--- a/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml
+++ b/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml
@@ -108,6 +108,8 @@ spec:
       description: Digest from signed Windows files
     - name: unsignedWindowsDigest
       description: Digest from unsigned Windows files
+    - name: publishedFiles
+      description: List of published files
   volumes:
     - name: shared-dir
       emptyDir: {}
@@ -842,7 +844,7 @@ spec:
           value: "$(params.snapshot_json)"
       script: |
         #!/usr/bin/env bash
-        set -eu
+        set -eux
 
         STDERR_FILE=/tmp/stderr.txt
 
@@ -881,18 +883,27 @@ spec:
             FILE=$(jq -c --arg i "$i" '.files[$i|tonumber]' <<< "$COMPONENT")
             SOURCE=$(jq -er '.source' <<< "$FILE") \
               || (echo "Missing files.source for component." && exit 1 )
-            BINARY=$(jq -er '.binary' <<< "$FILE")
-            case "${SOURCE}" in
-              (*darwin*)
-                tar -czf "${COMPRESSED_DIR}/${SOURCE}" -r "macos/${BINARY}"
-                ;;
-              (*linux*)
-                tar -czf "${COMPRESSED_DIR}/${SOURCE}" -r "linux/${BINARY}"
-                ;;
-              (*windows*)
-                zip -r "${COMPRESSED_DIR}/${SOURCE}" "windows/${BINARY}"
-                ;;
-            esac
+            DELIVERY_FORMAT=$(jq -r '.delivery_format // ["compressed"] | sort | .[]' <<< "$FILE")
+            for FORMAT in $DELIVERY_FORMAT; do
+              if [ "$FORMAT" = "compressed" ]; then
+                case "${SOURCE}" in
+                  (*darwin*)
+                    tar -czf "${COMPRESSED_DIR}/${SOURCE}" -r "${CONTENT_DIR}/macos/*"
+                    ;;
+                  (*linux*)
+                    tar -czf "${COMPRESSED_DIR}/${SOURCE}" -r "${CONTENT_DIR}/linux/*"
+                    ;;
+                  (*windows*)
+                    zip -r "${COMPRESSED_DIR}/${SOURCE}" "${CONTENT_DIR}/windows/*"
+                    ;;
+                esac
+              fi
+
+              # if "raw" is listed in the delivery_mode, make sure the binaries will be also pushed
+              if [ "$FORMAT" = "raw" ]; then
+                find "${CONTENT_DIR}/unsigned" "${CONTENT_DIR}/linux" -type f -exec cp "{}" "${COMPRESSED_DIR}/" \;
+              fi
+            done
           done
         }
 
@@ -990,6 +1001,8 @@ spec:
             if [ "$err" -eq 0 ] ; then
                 echo -n "Success" > "$(results.result.path)"
             else
+                # cleaning up the publishedFiles result to clean up space in the results buffer
+                echo > "$(results.publishedFiles.path)"
                 echo "$0: ERROR '$command' failed at line $line - exited with status $err" > "$(results.result.path)"
                 if [ -f "$STDERR_FILE" ] ; then
                     # save output to the task result excluding the trace log
@@ -1027,6 +1040,9 @@ spec:
         DISK_IMAGE_DIR="/shared/artifacts/compressed"
         export DISK_IMAGE_DIR
         RELATIVE_PATHS=""
+
+        # save the results
+        find "${DISK_IMAGE_DIR}" -type f -exec basename {} \; | tail -c 512 | tee "$(results.publishedFiles.path)"
 
         push_to_pulp() {
           # use the 1st component's version for STAGED_JSON
diff --git a/tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-only-cdn-only-raw.yaml b/tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-only-cdn-only-raw.yaml
--- a/tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-only-cdn-only-raw.yaml
+++ b/tasks/internal/push-artifacts-to-cdn-task/tests/test-push-artifacts-to-cdn-only-cdn-only-raw.yaml
@@ -2,11 +2,11 @@
 apiVersion: tekton.dev/v1
 kind: Pipeline
 metadata:
-  name: test-push-artifacts-to-cdn-fail-no-cgwproductname
+  name: test-push-artifacts-to-cdn-only-cdn-only-raw
 spec:
   description: |
-    Run the push-artifacts task with the component having no contentGateway.productName. This should
-    fail the task
+    Run the push-artifacts task and only push to CDN since the CGW config data is not present
+    in the snapshot, and will publish only "raw" files.
   tasks:
     - name: run-task
       taskRef:
@@ -21,28 +21,26 @@ spec:
                 {
                   "containerImage": "quay.io/org/tenant/qcow-disk-image/qcow2-disk-image@sha256:abcdef12345",
                   "contentGateway": {
+                    "filePrefix": "testproduct-",
                     "productCode": "Code",
+                    "productName": "MyName",
                     "productVersionName": "1.3-staging"
-                  },
-                  "staged": {
-                    "destination": "test-product-amd64",
-                    "version": "1.3"
                   },
                   "files": [
                     {
                       "filename": "testproduct-binary-windows-amd64.zip",
                       "source": "testproduct-binary-windows-amd64.zip",
-                      "delivery_format": ["compressed", "raw"]
+                      "delivery_format": ["raw"]
                     },
                     {
                       "filename": "testproduct-binary-darwin-amd64.tar.gz",
                       "source": "testproduct-binary-darwin-amd64.tar.gz",
-                      "delivery_format": ["compressed", "raw"]
+                      "delivery_format": ["raw"]
                     },
                     {
                       "filename": "testproduct-binary-linux-amd64.tar.gz",
                       "source": "testproduct-binary-linux-amd64.tar.gz",
-                      "delivery_format": ["compressed", "raw"]
+                      "delivery_format": ["raw"]
                     }
                   ],
                   "name": "testproduct"
@@ -71,22 +69,26 @@ spec:
       params:
         - name: result
           value: $(tasks.run-task.results.result)
+        - name: publishedFiles
+          value: $(tasks.run-task.results.publishedFiles)
       taskSpec:
         params:
           - name: result
             type: string
+          - name: publishedFiles
+            type: string
         steps:
           - name: check-result
             image: quay.io/konflux-ci/release-service-utils:7a1d88df0e5aa21f6219db2a8732af87eed7ed73
-            env:
-              - name: "RESULT"
-                value: '$(params.result)'
             script: |
               #!/usr/bin/env bash
               set -ex
-
-              EXPECTED="Component 1 is missing 'productName'"
-              if [[ "$RESULT" != *"$EXPECTED"* ]]; then
-                echo "Error: result should be \"$EXPECTED\""
+              # this grep uses extented regex mode (-E) to check if the files listed in the publishedFiles
+              # result do not end with .zip or .gz, as the push-artifacts-to-cdn-task task should upload
+              # only non-compressed files to the Content Gateway.
+              grep -vE '.*\.(zip|gz)$' <<< "$(params.publishedFiles)" \
+                || ( echo "Error: the task should publish only raw files to CGW" && exit 1 )
+              if [[ "$(params.result)" != "Success" ]]; then
+                echo Error: result task result expected to be Success but was not
                 exit 1
               fi
