refactor(RELEASE-1560): update to remove .contentGateway
* Update push-artifacts-to-cdn-task to use the new
  data format, using `components.files` instead
  of `components.staged`.

* Updates push-artifacts-to-cdn-task to use
  the refactored `publish-to-cgw` script.

* Updates schema to support the new format.

* updates the task extract-binaries-from-image
  to use`data.mapping.components[].name`

Signed-Off-By: Sean Conroy <sconroy@redhat.com>

diff --git a/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml b/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml
--- a/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml
+++ b/tasks/internal/push-artifacts-to-cdn-task/push-artifacts-to-cdn-task.yaml
@@ -119,7 +119,7 @@ spec:
         secretName: checksum-keytab-secret
   steps:
     - name: extract-artifacts
-      image: quay.io/konflux-ci/release-service-utils:7835e32b1974f956a6c942e24adbc79705cab12e
+      image: quay.io/konflux-ci/release-service-utils:937662a1ba4b345d3bd1f64b13ead1c31e7ac473
       computeResources:
         limits:
           memory: 512Mi
@@ -195,13 +195,13 @@ spec:
             AUTH_FILE=$(mktemp)
             select-oci-auth "${PULLSPEC}" > "$AUTH_FILE"
             oras pull --registry-config "$AUTH_FILE" "$PULLSPEC"
-            NUM_MAPPED_FILES=$(jq '.staged.files | length' <<< "${COMPONENT}")
+            NUM_MAPPED_FILES=$(jq '.files | length' <<< "${COMPONENT}")
             for ((i = 0; i < NUM_MAPPED_FILES; i++)) ; do
-                FILE=$(jq -c --arg i "$i" '.staged.files[$i|tonumber]' <<< "$COMPONENT")
+                FILE=$(jq -c --arg i "$i" '.files[$i|tonumber]' <<< "$COMPONENT")
                 SOURCE=$(jq -er '.source' <<< "$FILE") \
-                  || (echo "Missing staged.files.source for component." >&2 && exit 1 )
+                  || (echo "Missing files.source for component." >&2 && exit 1 )
                 FILENAME=$(jq -er '.filename' <<< "$FILE") \
-                  || (echo "Missing staged.files.filename for component." >&2 && exit 1 )
+                  || (echo "Missing files.filename for component." >&2 && exit 1 )
                 # The .qcow2 images are not zipped
                 if [ -f "${SOURCE}.gz" ] ; then
                     gzip -d "${SOURCE}.gz"
@@ -238,7 +238,7 @@ spec:
             wait -n
         done
     - name: push-unsigned-using-oras
-      image: quay.io/konflux-ci/release-service-utils:7835e32b1974f956a6c942e24adbc79705cab12e
+      image: quay.io/konflux-ci/release-service-utils:937662a1ba4b345d3bd1f64b13ead1c31e7ac473
       computeResources:
         limits:
           memory: 512Mi
@@ -351,7 +351,7 @@ spec:
         echo "Digest for windows content: $windows_digest"
         echo -n "$windows_digest" > "$(results.unsignedWindowsDigest.path)"
     - name: sign-mac-binaries
-      image: quay.io/konflux-ci/release-service-utils:7835e32b1974f956a6c942e24adbc79705cab12e
+      image: quay.io/konflux-ci/release-service-utils:937662a1ba4b345d3bd1f64b13ead1c31e7ac473
       computeResources:
         limits:
           memory: 512Mi
@@ -519,7 +519,7 @@ spec:
         # shellcheck disable=SC2029
         ssh "${SSH_OPTS[@]}" "${MAC_USER}@${MAC_HOST}" "rm -rf /tmp/$(context.taskRun.uid)"
     - name: sign-windows-binaries
-      image: quay.io/konflux-ci/release-service-utils:7835e32b1974f956a6c942e24adbc79705cab12e
+      image: quay.io/konflux-ci/release-service-utils:937662a1ba4b345d3bd1f64b13ead1c31e7ac473
       computeResources:
         limits:
           memory: 512Mi
@@ -657,7 +657,7 @@ spec:
         ssh $SSH_OPTS "Remove-Item -LiteralPath \
         C:\\Users\\${WINDOWS_USER}\\AppData\\Local\\Temp\\$(context.taskRun.uid) -Force -Recurse"
     - name: generate-checksums
-      image: quay.io/konflux-ci/release-service-utils:7835e32b1974f956a6c942e24adbc79705cab12e
+      image: quay.io/konflux-ci/release-service-utils:937662a1ba4b345d3bd1f64b13ead1c31e7ac473
       computeResources:
         limits:
           memory: 512Mi
@@ -821,7 +821,7 @@ spec:
         mv "$SHA_SUM_PATH" "${SIGNED_DIR}/sha256sum.txt"
 
     - name: compress-artifacts
-      image: quay.io/konflux-ci/release-service-utils:7835e32b1974f956a6c942e24adbc79705cab12e
+      image: quay.io/konflux-ci/release-service-utils:937662a1ba4b345d3bd1f64b13ead1c31e7ac473
       computeResources:
         limits:
           memory: 256Mi
@@ -870,11 +870,11 @@ spec:
         function compress_components {
           mkdir -p "$COMPRESSED_DIR"
           COMPONENT_JSON="$1"
-          NUM_MAPPED_FILES=$(jq '.staged.files | length' <<< "${COMPONENT_JSON}")
+          NUM_MAPPED_FILES=$(jq '.files | length' <<< "${COMPONENT_JSON}")
           for ((i = 0; i < NUM_MAPPED_FILES; i++)) ; do
-            FILE=$(jq -c --arg i "$i" '.staged.files[$i|tonumber]' <<< "$COMPONENT")
+            FILE=$(jq -c --arg i "$i" '.files[$i|tonumber]' <<< "$COMPONENT")
             SOURCE=$(jq -er '.source' <<< "$FILE") \
-              || (echo "Missing staged.files.source for component." && exit 1 )
+              || (echo "Missing files.source for component." && exit 1 )
             BINARY=$(jq -er '.binary' <<< "$FILE")
             case "${SOURCE}" in
               (*darwin*)
@@ -897,7 +897,7 @@ spec:
         done
 
     - name: push-artifacts
-      image: quay.io/konflux-ci/release-service-utils:7835e32b1974f956a6c942e24adbc79705cab12e
+      image: quay.io/konflux-ci/release-service-utils:937662a1ba4b345d3bd1f64b13ead1c31e7ac473
       computeResources:
         limits:
           memory: 512Mi
@@ -1020,58 +1020,8 @@ spec:
         DISK_IMAGE_DIR="/shared/artifacts/compressed"
         export DISK_IMAGE_DIR
 
-        process_component_for_developer_portal() { # Expected argument are [component json], [content_directory]
-          COMPONENT=$1
-
-          contentGatewayConfig="$(jq -c '.contentGateway // {}' <<< "${COMPONENT}")"
-          contentGatewayConfigSize="$(jq  '. | length' <<< "${contentGatewayConfig}")"
-          if [ "${contentGatewayConfigSize}" == "0" ]; then
-            echo "Configuration is not defined for Developer Portal publishing...skipping component"
-            return
-          fi
-
-          productName="$(jq -r '.productName' <<< "${contentGatewayConfig}")"
-          if [ "${productName}" == "null" ]; then
-            echo "Missing contentGateway.productName value for component. This should be an existing product" \
-                 "in the Developer Portal. Failing" >&2
-            exit 1
-          fi
-
-          productCode="$(jq -r '.productCode' <<< "${contentGatewayConfig}")"
-          if [ "${productCode}" == "null" ]; then
-            echo "Missing contentGateway.productCode value for component. This should be an existing product" >&2
-            exit 1
-          fi
-
-          productVersionName="$(jq -r '.productVersionName' <<< "${contentGatewayConfig}")"
-          if [ "${productVersionName}" == "null" ]; then
-            echo "Missing contentGateway.productVersionName value for component. This should be an existing" \
-                  "product in the Developer Portal. Failing" >&2
-            exit 1
-          fi
-
-          filePrefix="$(jq -r '.filePrefix' <<< "${contentGatewayConfig}")"
-          if [ "${filePrefix}" == "null" ]; then
-            echo "Missing contentGateway.filePrefix value for component. This should be the prefix for files to" \
-                 "upload to the Developer Portal. Failing" >&2
-            exit 1
-          fi
-
-          developer_portal_wrapper --debug --product-name "${productName}" \
-            --product-code "${productCode}" \
-            --product-version-name "${productVersionName}" \
-            --cgw-hostname "$(params.cgwHostname)" \
-            --content-directory "$2" \
-            --file-prefix "${filePrefix}"
-
-        }
-
-        # use the 1st component's version
+        # use the 1st component's version for STAGED_JSON
         VERSION=$(jq -cr '.components[0].staged.version // ""' <<< "$SNAPSHOT_JSON")
-        if [ "${VERSION}" == "" ] ; then
-          echo "Error: version not specified in .components[0].staged.version. Needed to publish to customer portal"
-          exit 1
-        fi
 
         # Change to the subdir with the images
         cd "${DISK_IMAGE_DIR}"
@@ -1093,27 +1043,41 @@ spec:
 
         # Check if staged.destination exists in any component
         HAS_STAGED_DESTINATION=$(jq 'any(.components[]?.staged?.destination; . != null)' <<< "$SNAPSHOT_JSON")
-        if [ "$HAS_STAGED_DESTINATION" = "true" ]; then
+        if [[ -n "$VERSION" && "$HAS_STAGED_DESTINATION" = "true" ]]; then
           echo "Pushing to customer portal (Pulp) with destination: $HAS_STAGED_DESTINATION"
           pulp_push_wrapper --debug --source "${DISK_IMAGE_DIR}" --pulp-url "$PULP_URL" \
             --pulp-cert $PULP_CERT_FILE --pulp-key $PULP_KEY_FILE --udcache-url "$UDC_URL" \
             2> "$STDERR_FILE"
+        elif [[ -z "$VERSION" && "$HAS_STAGED_DESTINATION" != "true" ]]; then
+          echo "Skipping Pulp push: staged.version is empty and components[].staged.destination is not set"
         else
-          echo "Skipping Pulp push: no staged.destination found in any component."
+          (echo "Error: Pulp push requires both staged.version and" \
+          "components[].staged.destination to be set" >&2 && exit 1) 2> "$STDERR_FILE"
         fi
 
         relative_paths=$(echo "$STAGED_JSON" | jq -erc .payload.files[].relative_path)
-        component_destinations=()
-        for path in $relative_paths:
-        do
-          parent_dir=$(dirname "$path")
-          component_destinations+=("${DISK_IMAGE_DIR}/$parent_dir")
+        NUM_COMPONENTS=$(jq '.components | length' <<< "$SNAPSHOT_JSON")
+        i=0
+        for path in $relative_paths; do
+          [[ $i -ge "$NUM_COMPONENTS" ]] && break  # stop once we've processed all components
+          component_destination="${DISK_IMAGE_DIR}/$(dirname "$path")"
+          
+          SNAPSHOT_JSON=$(
+            jq --argjson i "$i" --arg dir "$component_destination" '
+              .components[$i] |=
+                if .contentGateway? then
+                  .contentGateway.contentDir = $dir
+                else
+                  . # components without contentGateway will not be published. 
+                end
+            ' <<<"$SNAPSHOT_JSON"
+          )
+          ((++i))
         done
-
+          
         ## Process Files for Developer Portal / CGW
         ##
-        NUM_COMPONENTS=$(jq '.components | length' <<< "$SNAPSHOT_JSON")
-        for ((i = 0; i < NUM_COMPONENTS; i++)) ; do
-            COMPONENT=$(jq -c --arg i "$i" '.components[$i|tonumber]' <<< "$SNAPSHOT_JSON")
-            process_component_for_developer_portal "$COMPONENT" "${component_destinations[$i]}" 2> "$STDERR_FILE"
-        done
+        publish_to_cgw_wrapper \
+          --cgw_host "$(params.cgwHostname)" \
+          --data_json "$SNAPSHOT_JSON" \
+          2> >(tee "$STDERR_FILE" >&2)
