refactor(RELEASE-1797): create-pyxis-image uses repositories
This commit updates the create-pyxis-image managed task to read the
repositories key for each component instead of the repository key. This
is part of a larger effort for each component to specify multiple
repositories each instead of just one. Because apply-mapping emits both
repository and repositories now, the change does not have to be
backwards compatible.

Signed-off-by: Johnny Bieren <jbieren@redhat.com>

diff --git a/tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-one-arch.yaml b/tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-one-arch.yaml
--- a/tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-one-arch.yaml
+++ b/tasks/managed/create-pyxis-image/tests/test-create-pyxis-image-one-containerimage-one-arch.yaml
@@ -61,9 +61,22 @@ spec:
                   {
                     "name": "comp",
                     "containerImage": "source@sha256:mydigest",
-                    "repository": "registry.io/image",
-                    "tags": [
-                      "testtag"
+                    "repositories": [
+                      {
+                        "url": "registry.io/image1",
+                        "tags": [
+                          "testtag",
+                          "testtag2"
+                        ]
+                      },
+                      {
+                        "url": "registry.io/image2",
+                        "tags": [
+                          "a",
+                          "b",
+                          "c"
+                        ]
+                      }
                     ]
                   }
                 ]
@@ -158,8 +171,8 @@ spec:
               set -eux
 
               if [ "$(wc -l < "$(params.dataDir)"/mock_create_container_image.txt)" \
-                != 1 ]; then
-                echo Error: create_container_image was expected to be called 1 time. Actual calls:
+                != 2 ]; then
+                echo Error: create_container_image was expected to be called 2 time. Actual calls:
                 cat "$(params.dataDir)/mock_create_container_image.txt"
                 exit 1
               fi
@@ -186,27 +199,36 @@ spec:
                 exit 1
               fi
 
-              if [ "$(wc -l < "$(params.dataDir)"/mock_skopeo.txt)" != 1 ]; then
-                echo Error: skopeo was expected to be called 1 time. Actual calls:
-                cat "$(params.dataDir)/mock_skopeo.txt"
-                exit 1
-              fi
-
-              if [ "$(wc -l < "$(params.dataDir)"/mock_oras.txt)" != 2 ]; then
-                echo Error: oras was expected to be called 2 times. Actual calls:
+              if [ "$(wc -l < "$(params.dataDir)"/mock_oras.txt)" != 3 ]; then
+                echo Error: oras was expected to be called 3 times. Actual calls:
                 cat "$(params.dataDir)/mock_oras.txt"
                 exit 1
               fi
 
-              [ "$(head -n 1 < "$(params.dataDir)"/mock_skopeo.txt)" \
-                = "inspect --retry-times 3 --raw docker://registry.io/image@sha256:mydigest" ]
+              cat > "$(params.dataDir)/skopeo_expected_calls.txt" << EOF
+              inspect --retry-times 3 --raw docker://registry.io/image1@sha256:mydigest
+              inspect --retry-times 3 --raw docker://registry.io/image2@sha256:mydigest
+              EOF
+
+              mock_skopeo_calls="$(sort < "$(params.dataDir)/mock_skopeo.txt" | md5sum)"
+              # check that the actual calls match the expected calls
+              if [ "$(md5sum < "$(params.dataDir)/skopeo_expected_calls.txt")" \
+                != "${mock_skopeo_calls}" ]
+              then
+                echo "Error: Actual skopeo calls do not match expected calls."
+                echo Expected calls:
+                cat "$(params.dataDir)/skopeo_expected_calls.txt"
+                echo Actual calls:
+                echo "${mock_skopeo_calls}"
+                exit 1
+              fi
 
               # check if the correct arch and image id are set in the json file
-              jq -e '.components[0].pyxisImages[0] | ( .arch == "amd64" ) and ( .imageId == "0001" )
+              jq -e '.components[0].pyxisImages[0] | ( .arch == "amd64" ) and ( .imageId == "0002" )
                 and ( .os == "linux" )' "$(params.dataDir)/$(params.pyxisDataPath)"
 
-              if [ "$(wc -l < "$(params.dataDir)"/mock_select-oci-auth.txt)" != 2 ]; then
-                echo Error: select-oci-with was expected to be called 2 times. Actual calls:
+              if [ "$(wc -l < "$(params.dataDir)"/mock_select-oci-auth.txt)" != 3 ]; then
+                echo Error: select-oci-with was expected to be called 3 times. Actual calls:
                 cat "$(params.dataDir)/mock_select-oci-auth.txt"
                 exit 1
               fi
