fix(KFLUXBUGS-23): use data.fbc requestTimeout (#350)
- value for data.fbc.requestUpdateTimeout was never being consulted.

Signed-off-by: Scott Hebert <scoheb@gmail.com>

diff --git a/tasks/add-fbc-contribution/tests/test-add-fbc-contribution-timeout.yaml b/tasks/add-fbc-contribution/tests/test-add-fbc-contribution-timeout.yaml
--- a/tasks/add-fbc-contribution/tests/test-add-fbc-contribution-timeout.yaml
+++ b/tasks/add-fbc-contribution/tests/test-add-fbc-contribution-timeout.yaml
@@ -2,9 +2,9 @@
 apiVersion: tekton.dev/v1
 kind: Pipeline
 metadata:
-  name: test-add-fbc-contribution
+  name: test-add-fbc-contribution-timeout
 spec:
-  description: Test creating a internal request for the IIB pipeline
+  description: Test creating a internal request for the IIB pipeline that times-out early
   workspaces:
     - name: tests-workspace
   tasks:
@@ -41,8 +41,8 @@ spec:
                   "iibServiceConfigSecret": "test-iib-service-config-secret",
                   "iibOverwriteFromIndexCredential": "test-iib-overwrite-fromindex-credential",
                   "fbcPublishingCredentials": "test-fbc-publishing-credentials",
-                  "buildTimeoutSeconds": 420,
-                  "requestTimeoutSeconds": 120
+                  "buildTimeoutSeconds": 1,
+                  "requestTimeoutSeconds": 1
                 }
               }
               EOF
@@ -76,52 +76,11 @@ spec:
               #
               set -eux
 
-              internalRequest="$(kubectl get internalrequest --sort-by=.metadata.creationTimestamp --no-headers | \
-                tac | tail -1)"
-
-              requestParams=$(kubectl get internalrequest ${internalRequest} -o jsonpath="{.spec.params}")
-
-              if [ $(jq -r '.iibServiceConfigSecret' <<< "${requestParams}") != "test-iib-service-config-secret" ]; then
-                echo "iibServiceConfigSecret does not match"
+              if ! grep -q ' \-t 1' $(workspaces.data.path)/mock_internal-request.txt; then
+                echo "failed to detect correct timeout argument"
                 exit 1
               fi
 
-              value=$(jq -r '.iibOverwriteFromIndexCredential' <<< "${requestParams}")
-              if [ "${value}" != "test-iib-overwrite-fromindex-credential" ]
-              then
-                echo "iibOverwriteFromIndexCredential does not match"
-                exit 1
-              fi
-
-              if [ $(jq -r '.targetIndex' <<< "${requestParams}") != "quay.io/scoheb/fbc-target-index-testing:v4.12" ]
-              then
-                echo "targetIndex does not match"
-                exit 1
-              fi
-
-              if [ $(jq -r '.fromIndex' <<< "${requestParams}") != "quay.io/scoheb/fbc-index-testing:latest" ]; then
-                echo "fromIndex does not match"
-                exit 1
-              fi
-
-              value=$(jq -r '.binaryImage' <<< "${requestParams}")
-              if [ "${value}" != "registry.redhat.io/openshift4/ose-operator-registry:v4.12" ]
-              then
-                echo "binaryImage does not match"
-                exit 1
-              fi
-
-              if [ $(jq -r '.buildTimeoutSeconds' <<< "${requestParams}") != "420" ]
-              then
-                echo "buildTimeoutSeconds does not match"
-                exit 1
-              fi
-
-              if [ $(jq -r '.fbcFragment' <<< "${requestParams}") != "registry.io/image0@sha256:0000" ]
-              then
-                echo "fbcFragment does not match"
-                exit 1
-              fi
       runAfter:
         - run-task
   finally:
