feat: make collectors pipeline more generic
The new implementation allows to pass either a ReleasePlan
or a ReleasePlanAdmission.

Signed-off-by: David Moreno García <damoreno@redhat.com>

diff --git a/tasks/run-collectors/run-collectors.yaml b/tasks/run-collectors/run-collectors.yaml
--- a/tasks/run-collectors/run-collectors.yaml
+++ b/tasks/run-collectors/run-collectors.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: run-collectors
   labels:
-    app.kubernetes.io/version: "0.1.0"
+    app.kubernetes.io/version: "0.2.0"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -12,12 +12,12 @@ spec:
   description: >-
     Tekton task to run collectors defined in the ReleasePlan and ReleasePlanAdmission
   params:
-    - name: releasePlanAdmissionPath
+    - name: collectorsPath
       type: string
-      description: Path to the JSON string of the ReleasePlanAdmission in the data workspace
-    - name: releasePlanPath
+      description: Path to the JSON string of the resource containing the collectors in the data workspace
+    - name: collectorsResourceType
+      description: The type of resource that contains the collectors
       type: string
-      description: Path to the JSON string of the ReleasePlan in the data workspace
     - name: resultsDir
       type: string
       description: The relative path in the workspace to save the collector results to
@@ -33,8 +33,8 @@ spec:
 
         DEFAULT_TIMEOUT=900
         COLLECTORS_REPOSITORY="https://github.com/SOME_ORG/SOME_REPO" # TODO - update this once repo is created
-        RELEASEPLAN_FILE="$(workspaces.data.path)/$(params.releasePlanPath)"
-        RELEASEPLANADMISSION_FILE="$(workspaces.data.path)/$(params.releasePlanAdmissionPath)"
+        COLLECTORS_FILE="$(workspaces.data.path)/$(params.collectorsPath)"
+        COLLECTORS_RESOURCE_TYPE="$(params.collectorsResourceType)"
         RESULTS_DIR="$(workspaces.data.path)/$(params.resultsDir)"
         CONCURRENT_LIMIT=4
 
@@ -62,34 +62,32 @@ spec:
 
         git clone "${COLLECTORS_REPOSITORY}" collectors
         pushd collectors
+        
+        COLLECTORS_RESOURCE_TYPE=$(echo "$COLLECTORS_RESOURCE_TYPE" | tr '[:upper:]' '[:lower:]')
+
+        # Set COLLECTOR_TYPE based on the value of COLLECTORS_RESOURCE_TYPE
+        if [[ "$COLLECTORS_RESOURCE_TYPE" == "releaseplan" ]]; then
+          COLLECTOR_TYPE="tenant"
+        elif [[ "$COLLECTORS_RESOURCE_TYPE" == "releaseplanadmission" ]]; then
+          COLLECTOR_TYPE="managed"
+        else
+          echo "Error: Invalid COLLECTORS_RESOURCE_TYPE. Expected 'releaseplan' or 'releaseplanadmission'." >&2
+          exit 1
+        fi
 
         RUNNING_JOBS="\j" # Bash parameter for number of jobs currently running
 
-        if [ ! -f "${RELEASEPLAN_FILE}" ] ; then
-            echo "No valid releasePlan file was found so no tenant collectors will be run."
+        if [ ! -f "${COLLECTORS_FILE}" ] ; then
+            echo "No valid file was found so no collectors will be run."
         else
-            NUM_TENANT_COLLECTORS="$(jq '.spec.collectors | length' "${RELEASEPLAN_FILE}")"
-            for ((i = 0; i < NUM_TENANT_COLLECTORS; i++)) ; do
-                collector="$(jq -c --argjson i "$i" '.spec.collectors[$i]' "${RELEASEPLAN_FILE}")"
+            NUM_COLLECTORS="$(jq '.spec.collectors | length' "${COLLECTORS_FILE}")"
+            for ((i = 0; i < NUM_COLLECTORS; i++)) ; do
+                collector="$(jq -c --argjson i "$i" '.spec.collectors[$i]' "${COLLECTORS_FILE}")"
                 # Limit batch size to concurrent limit
                 while (( ${RUNNING_JOBS@P} >= "$CONCURRENT_LIMIT" )); do
                     wait -n
                 done
-                execute_collector "$collector" tenant &
-            done
-        fi
-
-        if [ ! -f "${RELEASEPLANADMISSION_FILE}" ] ; then
-            echo "No valid releasePlanAdmission file was found so no managed collectors will be run."
-        else
-            NUM_MANAGED_COLLECTORS="$(jq '.spec.collectors | length' "${RELEASEPLANADMISSION_FILE}")"
-            for ((i = 0; i < NUM_MANAGED_COLLECTORS; i++)) ; do
-                collector="$(jq -c --argjson i "$i" '.spec.collectors[$i]' "${RELEASEPLANADMISSION_FILE}")"
-                # Limit batch size to concurrent limit
-                while (( ${RUNNING_JOBS@P} >= "$CONCURRENT_LIMIT" )); do
-                    wait -n
-                done
-                execute_collector "$collector" managed &
+                execute_collector "$collector" "${COLLECTOR_TYPE}" &
             done
         fi
 
