fix(ISV-5658): fix shellcheck issues
Signed-off-by: Martin Jediny <jedinym@proton.me>

diff --git a/tasks/managed/push-sbom-to-s3/push-sbom-to-s3.yaml b/tasks/managed/push-sbom-to-s3/push-sbom-to-s3.yaml
--- a/tasks/managed/push-sbom-to-s3/push-sbom-to-s3.yaml
+++ b/tasks/managed/push-sbom-to-s3/push-sbom-to-s3.yaml
@@ -48,16 +48,14 @@ spec:
           region="us-east-1"
           bucket="$(params.retryS3Bucket)"
 
-          echo "Pushing "${to_upload}" to S3."
-          curl -X PUT \
-            --silent --show-error --fail-with-body --retry 5 \
-            --user "${aws_access_key_id}:${aws_secret_access_key}" \
-            --aws-sigv4 "aws:amz:${region}:s3" \
-            --upload-file "${to_upload}" \
-            "https://${bucket}.s3.${region}.amazonaws.com"
-
-          if [[ $? != 0 ]]; then
-             >&2 echo "ERROR: Failed to push SBOM to S3 bucket."
+          echo "Pushing $to_upload to S3."
+          if ! curl -X PUT \
+              --silent --show-error --fail-with-body --retry 5 \
+              --user "${aws_access_key_id}:${aws_secret_access_key}" \
+              --aws-sigv4 "aws:amz:${region}:s3" \
+              --upload-file "${to_upload}" \
+              "https://${bucket}.s3.${region}.amazonaws.com"; then
+            >&2 echo "ERROR: Failed to push SBOM to S3 bucket."
             exit 1
           fi
         done
