feat(ISV-5658): make sbom s3 push work with directories
Signed-off-by: Martin Jediny <jedinym@proton.me>

diff --git a/tasks/managed/push-sbom-to-s3/push-sbom-to-s3.yaml b/tasks/managed/push-sbom-to-s3/push-sbom-to-s3.yaml
--- a/tasks/managed/push-sbom-to-s3/push-sbom-to-s3.yaml
+++ b/tasks/managed/push-sbom-to-s3/push-sbom-to-s3.yaml
@@ -9,14 +9,16 @@ metadata:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
 spec:
-  description: |-
+  description: |
+    Push unuploaded SBOMs to S3 to retry the Atlas push.
   params:
     - name: retryAWSSecretName
       description: Name of the Secret containing AWS credentials for retry mechanism.
     - name: retryS3Bucket
       description: Name of the S3 bucket for the retry mechanism.
-    - name: sbomPath
-      description: Full path to the SBOM to be pushed to S3.
+    - name: sbomDir
+      description: |
+        Path to the directory in the data workspaces containing the SBOMs.
   workspaces:
     - name: data
   volumes:
@@ -36,23 +38,25 @@ spec:
         aws_access_key_id="$(cat /secrets/atlas-aws-access-key-id)"
         aws_secret_access_key="$(cat /secrets/atlas-aws-secret-access-key)"
 
-        # strip supported version suffix
-        sbom_path="$(params.sbomPath)"
-        to_upload="${sbom_path%.supported_version}"
-        cp "${sbom_path}" "${to_upload}"
+        shopt -s nullglob
+        for sbom in "$(workspaces.data.path)/$(params.sbomDir)"/*; do
+          # strip supported version suffix
+          to_upload="${sbom%.supported_version}"
+          cp "${sbom}" "${to_upload}"
 
-        region="us-east-1"
-        bucket="$(params.retryS3Bucket)"
+          region="us-east-1"
+          bucket="$(params.retryS3Bucket)"
 
-        echo "Pushing "${to_upload}" to S3."
-        curl -X PUT \
-          --silent --show-error --fail-with-body --retry 5 \
-          --user "${aws_access_key_id}:${aws_secret_access_key}" \
-          --aws-sigv4 "aws:amz:${region}:s3" \
-          --upload-file "${to_upload}" \
-          "https://${bucket}.s3.${region}.amazonaws.com"
+          echo "Pushing "${to_upload}" to S3."
+          curl -X PUT \
+            --silent --show-error --fail-with-body --retry 5 \
+            --user "${aws_access_key_id}:${aws_secret_access_key}" \
+            --aws-sigv4 "aws:amz:${region}:s3" \
+            --upload-file "${to_upload}" \
+            "https://${bucket}.s3.${region}.amazonaws.com"
 
-        if [[ $? != 0 ]]; then
-           >&2 echo "ERROR: Failed to push SBOM to S3 bucket."
-          exit 1
-        fi
+          if [[ $? != 0 ]]; then
+             >&2 echo "ERROR: Failed to push SBOM to S3 bucket."
+            exit 1
+          fi
+        done
diff --git a/tasks/managed/push-sbom-to-s3/tests/test-push-sbom-to-s3.yaml b/tasks/managed/push-sbom-to-s3/tests/test-push-sbom-to-s3.yaml
--- a/tasks/managed/push-sbom-to-s3/tests/test-push-sbom-to-s3.yaml
+++ b/tasks/managed/push-sbom-to-s3/tests/test-push-sbom-to-s3.yaml
@@ -21,9 +21,11 @@ spec:
               #!/usr/bin/env bash
               set -eux
 
-              mkdir -p "$(workspaces.data.path)/workdir/"
-              cd "$(workspaces.data.path)/workdir/"
-              touch "sbom.json.supported_version"
+              mkdir -p "$(workspaces.data.path)/sboms/"
+              cd "$(workspaces.data.path)/sboms/"
+
+              touch "sbom1.json.supported_version"
+              touch "sbom2.json.supported_version"
 
     - name: run-task
       taskRef:
@@ -33,8 +35,8 @@ spec:
           value: atlas-test-aws-secret
         - name: retryS3Bucket
           value: "bucket"
-        - name: sbomPath
-          value: "/workspace/data/workdir/sbom.json.supported_version"
+        - name: sbomDir
+          value: "sboms"
       workspaces:
         - name: data
           workspace: tests-workspace
@@ -56,15 +58,21 @@ spec:
             script: |
               #!/usr/bin/env bash
               set -eux
-              workdir="$(workspaces.data.path)/workdir"
+              workdir="$(workspaces.data.path)"
 
-              if [ "$(wc -l < "$workdir/mock_curl.txt")" != 1 ]; then
-                echo "TEST FAILED: curl was not called."
+              if [ "$(wc -l < "$workdir/mock_curl.txt")" != 2 ]; then
+                echo "TEST FAILED: curl was not called two times."
                 cat "$workdir/mock_curl.txt"
                 exit 1
               fi
 
-              if ! grep -q -- '--upload-file /workspace/data/workdir/sbom.json' "$workdir/mock_curl.txt"; then
+              if ! grep -q -- '--upload-file /workspace/data/sboms/sbom1.json' "$workdir/mock_curl.txt"; then
+                echo "TEST FAILED: Correct file not in curl call."
+                cat "$workdir/mock_curl.txt"
+                exit 1
+              fi
+
+              if ! grep -q -- '--upload-file /workspace/data/sboms/sbom2.json' "$workdir/mock_curl.txt"; then
                 echo "TEST FAILED: Correct file not in curl call."
                 cat "$workdir/mock_curl.txt"
                 exit 1
