fix(RELEASE-2203): check return code in marketplacesvm push
This commit updates the marketplacesvm-push-disk-images task to check
the return code of the background processes that run in parallel.
Previously, if one failed, the task would continue anyways, but this
fixes that.

Signed-off-by: Johnny Bieren <jbieren@redhat.com>

diff --git a/tasks/managed/marketplacesvm-push-disk-images/marketplacesvm-push-disk-images.yaml b/tasks/managed/marketplacesvm-push-disk-images/marketplacesvm-push-disk-images.yaml
--- a/tasks/managed/marketplacesvm-push-disk-images/marketplacesvm-push-disk-images.yaml
+++ b/tasks/managed/marketplacesvm-push-disk-images/marketplacesvm-push-disk-images.yaml
@@ -243,6 +243,7 @@ spec:
 
         # Process each component in parallel with memory-aware job management
         STABILIZATION_DELAY=2
+        success=true
         jobs_spawned=0
         jobs_collected=0
         for (( i = 0; i < NUM_COMPONENTS; i++ )); do
@@ -250,7 +251,7 @@ spec:
             # Wait for memory and concurrent limit before spawning
             wait_for_memory 80
             while (( ${RUNNING_JOBS@P} >= $(params.concurrentLimit) )); do
-                wait -n
+                wait -n || success=false
                 jobs_collected=$((jobs_collected + 1))
             done
 
@@ -265,9 +266,15 @@ spec:
         # Wait for all remaining jobs - use counter to collect all exit codes
         # in case processes finished during a stabilization sleep
         while (( jobs_collected < jobs_spawned )); do
-            wait -n
+            wait -n || success=false
             jobs_collected=$((jobs_collected + 1))
         done
+
+        # This is redundant since we have set -e, but makes things a bit more clear
+        if [ $success != "true" ]; then
+          echo "ERROR: prepare_component failed for at least one component"
+          exit 1
+        fi
 
         # Change to the base directory
         cd "${BASE_DIR}"
