feat(RELEASE-978): add image reference check in apply-mapping
containerImage values are required to use a sha reference. A check
was added for this. The task will fail if one or more images
use an invalid reference.

Signed-off-by: Martin Malina <mmalina@redhat.com>

diff --git a/tasks/apply-mapping/apply-mapping.yaml b/tasks/apply-mapping/apply-mapping.yaml
--- a/tasks/apply-mapping/apply-mapping.yaml
+++ b/tasks/apply-mapping/apply-mapping.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: apply-mapping
   labels:
-    app.kubernetes.io/version: "1.3.1"
+    app.kubernetes.io/version: "1.4.0"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -116,9 +116,18 @@ spec:
         NUM_MAPPED_COMPONENTS=$(jq '.components | length' "${SNAPSHOT_SPEC_FILE}")
         for ((i = 0; i < $NUM_MAPPED_COMPONENTS; i++)) ; do
             component=$(jq -c --argjson i "$i" '.components[$i]' "${SNAPSHOT_SPEC_FILE}")
+
+            # images are required to use sha reference - check this
+            NAME=$(jq -r '.name' <<< "$component")
+            IMAGE_REF=$(jq -r '.containerImage' <<< "$component")
+            if ! [[ "$IMAGE_REF" =~ ^[^:]+@sha256:[0-9a-f]+$ ]] ; then
+              echo "Component ${NAME} contains an invalid containerImage value. sha reference is required: ${IMAGE_REF}"
+              exit 1
+            fi
+
             imageTags=$(jq '.tags // []' <<< "$component")
             git_sha=$(jq -r '.source.git.revision' <<< "$component") # this sets the value to "null" if it doesn't exist
-            build_sha=$(jq -r '.containerImage' <<< "$component" | cut -d ':' -f 2)
+            build_sha=$(echo "$IMAGE_REF" | cut -d ':' -f 2)
             passedTimestampFormat=$(jq -r --arg default $defaultTimestampFormat \
               '.timestampFormat // $default' <<< "$component")
             timestamp="$(date -d "$currentTimestamp" "+$passedTimestampFormat")"
