feat(RELEASE-1116): timestamp variable is for build date
This commit modifies the apply-mapping task to treat the timestamp user
provided variable as the build timestamp instead of the current time. It
is found by inspecting the image's labels. The existing timestamp
functionality now exists under the release_timestamp variable.

Also, if a tag is translated with a null value, the task will now fail.

Signed-off-by: Johnny Bieren <jbieren@redhat.com>

diff --git a/tasks/apply-mapping/apply-mapping.yaml b/tasks/apply-mapping/apply-mapping.yaml
--- a/tasks/apply-mapping/apply-mapping.yaml
+++ b/tasks/apply-mapping/apply-mapping.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: apply-mapping
   labels:
-    app.kubernetes.io/version: "1.5.1"
+    app.kubernetes.io/version: "1.6.0"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -62,7 +62,8 @@ spec:
             exit 0
         fi
 
-        translate_tags () { # Expected arguments are [tags, timestamp, git sha, 7 character git sha, source sha]
+        # Expected arguments are [tags, timestamp, release_timestamp, git sha, 7 character git sha, source sha]
+        translate_tags () {
         # The tags argument is a json array
             if [[ $1 == '' ]] ; then
                 echo ''
@@ -72,12 +73,14 @@ spec:
             SUPPORTED_VARIABLES='[
                 {"{{timestamp}}": "'$2'"},
                 {"{{ timestamp }}": "'$2'"},
-                {"{{git_sha}}": "'$3'"},
-                {"{{ git_sha }}": "'$3'"},
-                {"{{git_short_sha}}": "'$4'"},
-                {"{{ git_short_sha }}": "'$4'"},
-                {"{{digest_sha}}": "'$5'"},
-                {"{{ digest_sha }}": "'$5'"}
+                {"{{release_timestamp}}": "'$3'"},
+                {"{{ release_timestamp }}": "'$3'"},
+                {"{{git_sha}}": "'$4'"},
+                {"{{ git_sha }}": "'$4'"},
+                {"{{git_short_sha}}": "'$5'"},
+                {"{{ git_short_sha }}": "'$5'"},
+                {"{{digest_sha}}": "'$6'"},
+                {"{{ digest_sha }}": "'$6'"}
             ]'
             tags=$1
 
@@ -86,6 +89,13 @@ spec:
                 variable=$(jq -c --argjson i "$i" '.[$i]' <<< "${SUPPORTED_VARIABLES}")
                 KEY=$(jq -r 'to_entries[] | .key' <<< "$variable")
                 VALUE=$(jq -r 'to_entries[] | .value' <<< "$variable")
+                # If a tag is going to be replaced by a null value, error out
+                if [[ "$VALUE" == "null" ]] && \
+                  [[ $(jq --arg key "$KEY" '. | map(select(test($key))) | length' <<< "$tags") -gt 0 ]] ; then
+                    echo "Requested substitution for key: $KEY but calculated value for it was null"
+                    echo "Failing..."
+                    exit 1
+                fi
                 tags=$(echo -n "$tags" | sed "s/$KEY/$VALUE/g")
             done
 
@@ -186,11 +196,22 @@ spec:
             build_sha=$(echo "$IMAGE_REF" | cut -d ':' -f 2)
             passedTimestampFormat=$(jq -r --arg default "$defaultTimestampFormat" \
               '.timestampFormat // $default' <<< "$component")
-            timestamp="$(date -d "$currentTimestamp" "+$passedTimestampFormat")"
+            release_timestamp="$(date -d "$currentTimestamp" "+$passedTimestampFormat")"
+            arch_json="$(get-image-architectures "${IMAGE_REF}")"
+            # The build-date label is not the same per architecture, but we don't support separate tags per arch. So,
+            # we just use the first digest listed
+            arch="$(jq -rs 'map(.platform.architecture) | .[0]' <<< "$arch_json")"
+            os="$(jq -rs 'map(.platform.os) | .[0]' <<< "$arch_json")"
+            build_date="$(skopeo inspect --no-tags --override-os "${os}" --override-arch "${arch}" \
+              docker://"${IMAGE_REF}" | jq -r '.Labels."build-date"')"
+            timestamp="$(date -d "${build_date}" "+$passedTimestampFormat")"
+            if [ "${build_date}" == "null" ] ; then
+              timestamp="null"
+            fi
 
             allTagsPreSubstitution=$(jq -n --argjson defaults "$defaultTags" --argjson imageTags \
               "$imageTags" '$defaults? + $imageTags? | unique')
-            tags=$(translate_tags "${allTagsPreSubstitution}" "${timestamp}" "${git_sha}" \
+            tags=$(translate_tags "${allTagsPreSubstitution}" "${timestamp}" "${release_timestamp}" "${git_sha}" \
               "${git_sha:0:7}" "${build_sha}")
             if [ "$(jq 'length' <<< "$tags")" -gt 0 ] ; then
               jq --argjson i "$i" --argjson updatedTags "$tags" '.components[$i].tags = $updatedTags' \
@@ -202,8 +223,8 @@ spec:
             for ((j = 0; j < STAGED_FILES; j++)) ; do
                 file=$(jq -c --argjson j "$j" '.staged.files[$j]' <<< "$component")
                 filenameArrayPreSubstitution=$(jq '.filename' <<< "$file" | jq -cs)
-                subbedFilename=$(translate_tags "${filenameArrayPreSubstitution}" "${timestamp}" "${git_sha}" \
-                  "${git_sha:0:7}" "${build_sha}" | jq -r '.[0]')
+                subbedFilename=$(translate_tags "${filenameArrayPreSubstitution}" "${timestamp}" \
+                  "${release_timestamp}" "${git_sha}" "${git_sha:0:7}" "${build_sha}" | jq -r '.[0]')
                 jq --argjson i "$i" --argjson j "$j" --arg filename "$subbedFilename" \
                   '.components[$i].staged.files[$j].filename = $filename' "${SNAPSHOT_SPEC_FILE}" > /tmp/temp \
                   && mv /tmp/temp "${SNAPSHOT_SPEC_FILE}"
