fix(KFLUXVNGD-203): remove sha prefix
- Remove sha @ prefix as it is already in the sha variable
- Update unit tests to test the ec command

Signed-off-by: Avi Biton <abiton@redhat.com>

diff --git a/tasks/managed/update-trusted-tasks/tests/test-update-trusted-tasks-success-multiple-tags.yaml b/tasks/managed/update-trusted-tasks/tests/test-update-trusted-tasks-success-multiple-tags.yaml
--- a/tasks/managed/update-trusted-tasks/tests/test-update-trusted-tasks-success-multiple-tags.yaml
+++ b/tasks/managed/update-trusted-tasks/tests/test-update-trusted-tasks-success-multiple-tags.yaml
@@ -72,7 +72,7 @@ spec:
           - name: check-result
             image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
             script: |
-              #!/usr/bin/env sh
+              #!/bin/bash
               set -eux
 
               if [ "$(wc -l < "$(workspaces.data.path)/mock_skopeo.txt")" != 3 ]; then
@@ -87,5 +87,27 @@ spec:
                 exit 1
               fi
 
+              all_found=true
+              outs=(
+                "track bundle --bundle quay.io/notexist/task-echo:0.1@sha256:abcde \
+              --output oci:quay.io/notexist/data-acceptable-bundles:latest"
+
+                "track bundle --bundle quay.io/notexist/task-echo:test@sha256:abcde \
+              --output oci:quay.io/notexist/data-acceptable-bundles:latest"
+
+                "track bundle --bundle quay.io/notexist/task-echo:stage@sha256:abcde \
+              --output oci:quay.io/notexist/data-acceptable-bundles:latest"
+              )
+              
+              for out in "${outs[@]}"; do
+                if ! grep -qF -- "$out" "$(workspaces.data.path)/mock_ec.txt"; then
+                  echo "Error: $out was not found in the ec command"
+                  all_found=false
+                fi
+              done
+              if ! $all_found; then
+                cat "$(workspaces.data.path)/mock_ec.txt"
+                exit 1
+              fi 
       runAfter:
         - run-task
diff --git a/tasks/managed/update-trusted-tasks/tests/test-update-trusted-tasks-success-no-latest.yaml b/tasks/managed/update-trusted-tasks/tests/test-update-trusted-tasks-success-no-latest.yaml
--- a/tasks/managed/update-trusted-tasks/tests/test-update-trusted-tasks-success-no-latest.yaml
+++ b/tasks/managed/update-trusted-tasks/tests/test-update-trusted-tasks-success-no-latest.yaml
@@ -71,7 +71,7 @@ spec:
           - name: check-result
             image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
             script: |
-              #!/usr/bin/env sh
+              #!/bin/bash
               set -eux
 
               if [ "$(wc -l < "$(workspaces.data.path)/mock_skopeo.txt")" != 1 ]; then
@@ -85,9 +85,13 @@ spec:
                 cat "$(workspaces.data.path)/mock_ec.txt"
                 exit 1
               fi
-
-              if grep -q -- '--input' "$(workspaces.data.path)/mock_ec.txt"; then
-                echo "Error: The ec command should not contain --input option"
+              
+              out="track bundle --bundle quay.io/notexist/task-echo:0.1@sha256:abcde \
+              --output oci:quay.io/notexist/data-acceptable-bundles:latest"
+              
+              if ! grep -qF -- "$out" "$(workspaces.data.path)/mock_ec.txt"; then
+                echo "Error: $out was not found in the ec command"
+                cat "$(workspaces.data.path)/mock_ec.txt"
                 exit 1
               fi
       runAfter:
