fix: add support for internal pyxis endpoints
- with the introduction of Konflux internal clusters,
  we need to interact with internal pyxis endpoints.

Signed-off-by: Scott Hebert <scoheb@gmail.com>

diff --git a/tasks/publish-pyxis-repository/publish-pyxis-repository.yaml b/tasks/publish-pyxis-repository/publish-pyxis-repository.yaml
--- a/tasks/publish-pyxis-repository/publish-pyxis-repository.yaml
+++ b/tasks/publish-pyxis-repository/publish-pyxis-repository.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: publish-pyxis-repository
   labels:
-    app.kubernetes.io/version: "0.2.1"
+    app.kubernetes.io/version: "0.2.2"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -23,7 +23,7 @@ spec:
   params:
     - name: server
       type: string
-      description: The server type to use. Options are 'production' and 'stage'
+      description: The server type to use. Options are 'production','production-internal,'stage-internal' and 'stage'.
       default: production
     - name: pyxisSecret
       type: string
@@ -62,13 +62,19 @@ spec:
 
         if [[ "$(params.server)" == "production" ]]
         then
-            PYXIS_URL="https://pyxis.api.redhat.com"
+          PYXIS_URL="https://pyxis.api.redhat.com"
         elif [[ "$(params.server)" == "stage" ]]
         then
-            PYXIS_URL="https://pyxis.preprod.api.redhat.com"
+          PYXIS_URL="https://pyxis.preprod.api.redhat.com"
+        elif [[ "$(params.server)" == "production-internal" ]]
+        then
+          PYXIS_URL="https://pyxis.engineering.redhat.com"
+        elif [[ "$(params.server)" == "stage-internal" ]]
+        then
+          PYXIS_URL="https://pyxis.stage.engineering.redhat.com"
         else
-            echo "Invalid server parameter. Only 'production' and 'stage' are allowed."
-            exit 1
+          echo "Invalid server parameter. Only 'production','production-internal,'stage-internal' and 'stage' allowed."
+          exit 1
         fi
 
         echo "${pyxisCert}" > /tmp/crt
