feat(RELEASE-969): support multiple components in extract-binaries task (#443)
This commit adds support for handling multiple components within
a single snapshot with the extract-binaries-from-image task.

Signed-off-by: Scott Wickersham <swickers@redhat.com>

diff --git a/tasks/extract-binaries-from-image/extract-binaries-from-image.yaml b/tasks/extract-binaries-from-image/extract-binaries-from-image.yaml
--- a/tasks/extract-binaries-from-image/extract-binaries-from-image.yaml
+++ b/tasks/extract-binaries-from-image/extract-binaries-from-image.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: extract-binaries-from-image
   labels:
-    app.kubernetes.io/version: "1.2.0"
+    app.kubernetes.io/version: "2.0.0"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -21,6 +21,10 @@ spec:
       description: Path to the JSON string of the mapped Snapshot spec in the data workspace
     - name: subdirectory
       description: Subdirectory inside the workspace to be used for storing the binaries
+      type: string
+      default: ""
+    - name: dataPath
+      description: Path to the JSON string of the merged data to use in the data workspace
       type: string
       default: ""
   results:
@@ -41,28 +45,48 @@ spec:
             echo "Error: No valid snapshot file was provided."
             exit 1
         fi
-        IMAGE_URL=$(jq -r '.components[0].containerImage // ""' "${SNAPSHOT_SPEC_FILE}")
-        if [ -z "${IMAGE_URL}" ] ; then
-            echo "Error: Unable to get image url from snapshot."
-            exit 1
-        fi
 
         BINARIES_DIR=binaries
         BINARIES_PATH=$(workspaces.data.path)/$(params.subdirectory)/$BINARIES_DIR
         mkdir -p $BINARIES_PATH
 
-        TMP_DIR=$(mktemp -d)
-        skopeo copy docker://$IMAGE_URL dir:$TMP_DIR
+        DATA_FILE="$(workspaces.data.path)/$(params.dataPath)"
+        DESIRED_COMPONENTS_LIST=()
+        if [ ! -f "${DATA_FILE}" ] ; then
+            echo "No data JSON was provided."
+        elif [ $(jq '."content-gateway" | has("components")' "${DATA_FILE}") = true ]; then
+            DESIRED_COMPONENTS_LIST=$(jq -r '."content-gateway".components[].name' "${DATA_FILE}")
+        fi
 
-        cd $TMP_DIR
+        NUM_COMPONENTS=$(jq '.components | length' "$SNAPSHOT_SPEC_FILE")
+        for ((i=0; i < NUM_COMPONENTS; i++)); do
+          COMPONENT=$(jq -c ".components[$i]" "$SNAPSHOT_SPEC_FILE")
+          COMPONENT_NAME=$(echo $COMPONENT | jq -r '.name')
 
-        for DIGEST in $(jq -r ".layers[].digest" manifest.json)
-        do
-            FILE=${DIGEST#sha256:}
-            tar -xzvf $FILE
+          # If desired components list is not empty and COMPONENT_NAME is not in desired components list, skip
+          if [ -n "$DESIRED_COMPONENTS_LIST" ] && ! echo "$DESIRED_COMPONENTS_LIST" | grep -qw "$COMPONENT_NAME"; then
+            continue
+          fi
+
+          IMAGE_URL=$(echo $COMPONENT | jq -r '.containerImage // ""')
+          if [ -z "${IMAGE_URL}" ] ; then
+              echo "Error: Unable to get image url from snapshot."
+              exit 1
+          fi
+
+          TMP_DIR=$(mktemp -d)
+          skopeo copy docker://$IMAGE_URL dir:$TMP_DIR
+
+          cd $TMP_DIR
+
+          for DIGEST in $(jq -r ".layers[].digest" manifest.json)
+          do
+              FILE=${DIGEST#sha256:}
+              tar -xzvf $FILE
+          done
+
+          cp "$IMAGE_PATH"/* $BINARIES_PATH/
         done
-
-        cp "$IMAGE_PATH"/* $BINARIES_PATH/
 
         echo -n $(params.subdirectory)/$BINARIES_DIR | tee $(results.binaries_path.path)
       env:
