fix(KONFLUX-14665): check also internalrequest status
This PR adds a check of the internal-request status after
the publish happened as in case of time-out, there will be
no error to be caught, instead we will have a IR failed
condition.

Assisted-By: Claude
Signed-off-by: Leandro Mendes <lmendes@redhat.com>

diff --git a/tasks/managed/publish-index-image/publish-index-image.yaml b/tasks/managed/publish-index-image/publish-index-image.yaml
--- a/tasks/managed/publish-index-image/publish-index-image.yaml
+++ b/tasks/managed/publish-index-image/publish-index-image.yaml
@@ -197,7 +197,18 @@ spec:
               internalRequest=$(awk -F"'" '/created/ { print $2 }' "$IR_RESULT_FILE")
               echo "done (${internalRequest})"
 
-              results=$(kubectl get internalrequest "${internalRequest}" -o=jsonpath='{.status.results}')
+              # get the internal request status
+              internalRequestJson="$(kubectl get internalrequest "${internalRequest}" -o json | jq -c)"
+ 
+              status="$(jq '.status.conditions[].status' <<< "$internalRequestJson")"
+              if [ "$status" = "False" ]; then
+                errorMessage="$(jq '.status.conditions[].message' <<< "$internalRequestJson")"
+                echo "ERROR: Publish to ${publishingImages[$x]} failed"
+                echo "errorMessage: $errorMessage"
+                exit 1
+              fi
+
+              results=$(jq '.status.results' <<< "$internalRequestJson")
               requestMessage=$(echo "${results}" | jq -r '.requestMessage // ""')
 
               if echo "${requestMessage}" | grep -qi "error"; then
