feat(RELEASE-1176): only sign registry.access if required
`rh-sign-image` and `rh-sign-image-cosign` will now only
sign registry.access.redhat.com
references if requires_terms is false in the corresponding
repository object in Pyxis.

If require_terms is true (the vast majority of repos),
signing of registry.access references will be skipped
which will result in 50 % reduction of signing
requests.

Several changes are included:

* `publish-pyxis-repository` provides a new result that points
  to a file that contains a list of repos where signing
  of registry.access references is needed.
* `rh-sign-image` and `rh-sign-image-cosign` take this result
  as a new mandatory parameter
  and will skip registry.access signing unless the given repo
  is included in the file.
* `rh-advisories` and `rh-push-to-registry-redhat-io` pipelines
  were modified for this. The order of tasks was also slightly
  modified so that `publish-pyxis-repository` runs earlier
  in the pipeline.

Signed-off-by: Martin Malina <mmalina@redhat.com>

diff --git a/tasks/publish-pyxis-repository/tests/test-publish-pyxis-repository-no-terms-required.yaml b/tasks/publish-pyxis-repository/tests/test-publish-pyxis-repository-no-terms-required.yaml
--- a/tasks/publish-pyxis-repository/tests/test-publish-pyxis-repository-no-terms-required.yaml
+++ b/tasks/publish-pyxis-repository/tests/test-publish-pyxis-repository-no-terms-required.yaml
@@ -2,10 +2,11 @@
 apiVersion: tekton.dev/v1
 kind: Pipeline
 metadata:
-  name: test-publish-pyxis-repository
+  name: test-publish-pyxis-repository-no-terms-required
 spec:
   description: |
-    Run the publish-pyxis-repository task with multiple components and verify catalog URLs.
+    Run the publish-pyxis-repository task with multiple components where some of them
+    don't require terms, so these should be included in the signRegistryAccessPath result.
   workspaces:
     - name: tests-workspace
   tasks:
@@ -34,11 +35,11 @@ spec:
                     "name": "component1"
                   },
                   {
-                    "repository": "quay.io/redhat-prod/my-product----my-image2",
+                    "repository": "quay.io/redhat-prod/my-product----my-image5",
                     "name": "component2"
                   },
                   {
-                    "repository": "quay.io/redhat-prod/my-product----my-image3",
+                    "repository": "quay.io/redhat-prod/my-product----my-image6",
                     "name": "component3"
                   }
                 ]
@@ -102,11 +103,11 @@ spec:
                   },
                   {
                     "name": "component2",
-                    "url": "https://catalog.redhat.com/software/containers/my-product/my-image2/3"
+                    "url": "https://catalog.redhat.com/software/containers/my-product/my-image5/3"
                   },
                   {
                     "name": "component3",
-                    "url": "https://catalog.redhat.com/software/containers/my-product/my-image3/5"
+                    "url": "https://catalog.redhat.com/software/containers/my-product/my-image6/5"
                   }
                 ]
               }'
@@ -130,18 +131,24 @@ spec:
               [[ $(cat $(workspaces.data.path)/mock_curl.txt | head -n 2 | tail -n 1) \
                   == *"/id/1 "* ]]
               [[ $(cat $(workspaces.data.path)/mock_curl.txt | head -n 3 | tail -n 1) \
-                  == *"/my-product/my-image2 "* ]]
+                  == *"/my-product/my-image5 "* ]]
               [[ $(cat $(workspaces.data.path)/mock_curl.txt | head -n 4 | tail -n 1) \
                   == *"/id/3 "* ]]
               [[ $(cat $(workspaces.data.path)/mock_curl.txt | head -n 5 | tail -n 1) \
-                  == *"/my-product/my-image3 "* ]]
+                  == *"/my-product/my-image6 "* ]]
               [[ $(cat $(workspaces.data.path)/mock_curl.txt | head -n 6 | tail -n 1) \
                   == *"/id/5 "* ]]
 
+              EXPECTED_RESULTS='my-product/my-image5
+              my-product/my-image6'
+
               SIGN_ACCESS_FILE="$(workspaces.data.path)/$(params.signRegistryAccessPath)"
-              if [ "$(wc -l < "$SIGN_ACCESS_FILE")" != 0 ]; then
-                echo "Error: The signRegistryAccessPath file was expected to be empty. Instead, it contains:"
+              if [ "$(cat "$SIGN_ACCESS_FILE")" != "$EXPECTED_RESULTS" ]; then
+                echo "Error: The signRegistryAccessPath file was expected to contain:"
+                echo "$EXPECTED_RESULTS"
+                echo "Instead it contains:"
                 cat "$SIGN_ACCESS_FILE"
+                exit 1
               fi
       runAfter:
         - run-task
