feat(RELEASE-1192): use pipelineruns for signing (#585)
- in the case of private, internal clusters we can do away
  with using internal-services and just use pipelinesruns
- this PR includes a copy of the signing pipelines and tasks
  which have been altered to work with the tekton git resolvers
- 2 new scripts are used to start and wait for pipelineruns
- Added change to permit retry on request failures
- Add support for checking if signature exists for a given
  manifest digest and reference before attempting to create
  a new request.
- Concurrent limit is now 16 for creating internal pipelineruns
  or internal requests

Some additional improvements:
- add new WORKERS param for EC task and set default to 4
- Increase timeout for EC validation to be 1hr
- add 5 retries at simple signing pipeline level
- Ensure check-data-keys runs after signing
  - Otherwise, check-data-keys may timeout while rh-sign-image
    is executing



review fixes

- revert check-data-keys ordering
- restore set -x at top of rh-sign-image
- improve request composition of extra params



review and test fixes



additional review fixes

Signed-off-by: Scott Hebert <scoheb@gmail.com>

diff --git a/tasks/rh-sign-image/tests/test-rh-sign-image-single-component-plr-alreadysigned.yaml b/tasks/rh-sign-image/tests/test-rh-sign-image-single-component-plr-alreadysigned.yaml
--- a/tasks/rh-sign-image/tests/test-rh-sign-image-single-component-plr-alreadysigned.yaml
+++ b/tasks/rh-sign-image/tests/test-rh-sign-image-single-component-plr-alreadysigned.yaml
@@ -2,15 +2,9 @@
 apiVersion: tekton.dev/v1
 kind: Pipeline
 metadata:
-  name: test-rh-sign-image-timeout
-  annotations:
-    test/assert-task-failure: "run-task"
+  name: test-rh-sign-image-single-component-plr-alreadysigned
 spec:
-  description: >
-    Test a scenario when the IR processing times out. The timeout happens
-    because the requestTimeout parameter of the task is set to 1 and this
-    is passed to the wait-for-internal-request call. So the mock would mark the IR as passed
-    in 10 seconds, but it will time out before that happens.
+  description: Test creating an internal pipelinerun to sign an image but the signature already exists
   workspaces:
     - name: tests-workspace
   tasks:
@@ -34,12 +28,16 @@ spec:
                 "components": [
                   {
                     "name": "comp0",
+                    "source": {
+                      "git": {
+                        "revision": "deadbeef"
+                      }
+                    },
                     "containerImage": "registry.io/image0@sha256:0000",
                     "repository": "quay.io/redhat-prod/myproduct----myrepo",
-                    "rh-registry-repo": "registry.redhat.io/myproduct/myrepo",
-                    "registry-access-repo": "registry.access.redhat.com/myproduct/myrepo",
+                    "rh-registry-repo": "registry.redhat.io/already/signed",
+                    "registry-access-repo": "registry.access.redhat.com/already/signed",
                     "tags": [
-                      "some-prefix-12345",
                       "some-prefix"
                     ]
                   }
@@ -49,8 +47,14 @@ spec:
 
               cat > "$(workspaces.data.path)/data.json" << EOF
               {
+                "mapping": {
+                  "defaults": {
+                    "pushSourceContainer": "false"
+                  }
+                },
                 "sign": {
-                  "request": "hacbs-signing-pipeline",
+                  "request": "simple-signing-pipeline",
+                  "requestType": "internal-pipelinerun",
                   "configMapName": "signing-config-map"
                 }
               }
@@ -86,9 +90,7 @@ spec:
         name: rh-sign-image
       params:
         - name: requester
-          value: testuser-timeout
-        - name: requestTimeout
-          value: 1
+          value: testuser-single
         - name: pipelineRunUid
           value: $(context.pipelineRun.uid)
         - name: snapshotPath
@@ -108,14 +110,36 @@ spec:
           workspace: tests-workspace
       runAfter:
         - setup
-  finally:
-    - name: cleanup
+    - name: check-result
+      workspaces:
+        - name: data
+          workspace: tests-workspace
       taskSpec:
         steps:
-          - name: delete-crs
+          - name: check-result
             image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
             script: |
               #!/usr/bin/env bash
               set -eux
 
-              kubectl delete internalrequests --all
+              internalPipelineruns="$(kubectl get pr \
+                -l "internal-services.appstudio.openshift.io/pipelinerun-uid=$(context.pipelineRun.uid)" \
+                -o json --sort-by=.metadata.creationTimestamp | jq -c)"
+              plrsLength=$(jq ".items | length" <<< "${internalPipelineruns}" )
+
+              if [ "${plrsLength}" != "0" ] ; then
+                echo "Error: seems pipelineruns were created, but signatures were supposed to be skipped"
+                exit 1
+              fi
+      runAfter:
+        - run-task
+  finally:
+    - name: cleanup
+      taskSpec:
+        steps:
+          - name: delete-plrs
+            image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
+            script: |
+              #!/usr/bin/env bash
+              set -eux
+              kubectl delete pr -l "internal-services.appstudio.openshift.io/pipelinerun-uid=$(context.pipelineRun.uid)"
