refactor(RELEASE-2030): make atlas mandatory when used
This commit updates the rh-advisories and push-rpms-to-pulp pipeline to
make the atlas params required. They were optional for a while, but now
all users using these pipelines should have the atlas configs defined.
Consequently, it updates the collect-atlas-params task to fail when
called if the atlas keys are missing in the data file, instead of
exiting with the results as empty strings.

Signed-off-by: Johnny Bieren <jbieren@redhat.com>

diff --git a/tasks/managed/collect-atlas-params/collect-atlas-params.yaml b/tasks/managed/collect-atlas-params/collect-atlas-params.yaml
--- a/tasks/managed/collect-atlas-params/collect-atlas-params.yaml
+++ b/tasks/managed/collect-atlas-params/collect-atlas-params.yaml
@@ -11,8 +11,7 @@ spec:
     Tekton task that collects the Atlas server option from the data file. Based on
     the value of the "atlas.server" field ("stage" or "production"), outputs results
     used to push SBOMs to Atlas. Also outputs results used to push SBOMs to an S3
-    bucket. If no Atlas fields are present in the data file, it outputs empty
-    strings as results, indicating that the Atlas push should be skipped.
+    bucket. If no Atlas fields are present in the data file, the task fails
   params:
     - name: dataPath
       type: string
@@ -148,14 +147,7 @@ spec:
         fi
 
         atlasServer=$(jq -r '.atlas.server' "$DATA_FILE")
-        if [ "$atlasServer" = "null" ]; then
-            # In this case, SBOM processing will be skipped.
-            atlasApiUrl=""
-            ssoTokenUrl=""
-            secretName=""
-            retryAWSSecretName=""
-            retryS3Bucket=""
-        elif [ "$atlasServer" = "stage" ]; then
+        if [ "$atlasServer" = "stage" ]; then
             atlasApiUrl="https://atlas.release.stage.devshift.net"
             ssoTokenUrl="https://auth.stage.redhat.com/auth/realms/EmployeeIDP/protocol/openid-connect/token"
             secretName=$(jq -r '.atlas."atlas-sso-secret-name" // "atlas-staging-sso-secret"' "$DATA_FILE")
@@ -169,6 +161,10 @@ spec:
             retryAWSSecretName=$(jq -r '.atlas."atlas-retry-aws-secret-name" // "atlas-retry-s3-production-secret"' \
               "$DATA_FILE")
             retryS3Bucket="mpp-e1-prod-sbom-e02138d3-5c5c-4d90-a38f-6c54f658604d"
+        elif [ "$atlasServer" = "null" ]; then
+            echo "ERROR: .atlas.server value is missing from the data file. This field is mandatory."
+            echo "Consult with your release engineering contact to ask why you are missing this value"
+            exit 1
         else
             echo "ERROR: Unknown .atlas.server value '$atlasServer'. Expected 'stage' or 'production'."
             exit 1
