fix: allow collect-task-params results to be empty
Some collect-*-params task return the empty string as a result. This is
not currently possible with collect-task-params; it sees a default value
of the empty string as it missing. This commit fixes the task to allow
the empty string to be used as a default value.

Signed-off-by: Johnny Bieren <jbieren@redhat.com>

diff --git a/tasks/managed/collect-task-params/tests/test-collect-task-params.yaml b/tasks/managed/collect-task-params/tests/test-collect-task-params.yaml
--- a/tasks/managed/collect-task-params/tests/test-collect-task-params.yaml
+++ b/tasks/managed/collect-task-params/tests/test-collect-task-params.yaml
@@ -111,7 +111,8 @@ spec:
               {"resultIndex": 1, "key": ".foo.bar"},
               {"resultIndex": 2, "key": ".simpleValue"},
               {"resultIndex": 3, "key": ".missingKey", "default": "default_value"},
-              {"resultIndex": 4, "key": ".numberValue", "default": "42"}
+              {"resultIndex": 4, "key": ".numberValue", "default": "42"},
+              {"resultIndex": 5, "key": ".missingemptydefault", "default": ""}
             ]
         - name: ociStorage
           value: $(params.ociStorage)
@@ -146,6 +147,8 @@ spec:
           value: $(tasks.run-task.results.extractedValues[3])
         - name: defaultNumberValue
           value: $(tasks.run-task.results.extractedValues[4])
+        - name: emptyDefaultValue
+          value: $(tasks.run-task.results.extractedValues[5])
       taskSpec:
         params:
           - name: arrayValue
@@ -153,6 +156,7 @@ spec:
           - name: simpleValue
           - name: defaultStringValue
           - name: defaultNumberValue
+          - name: emptyDefaultValue
         steps:
           - name: verify-results
             image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
@@ -182,5 +186,10 @@ spec:
 
               if [ "$(params.defaultNumberValue)" != "42" ]; then
                 echo "Error: Expected index 4 to be '42', got $(params.defaultNumberValue)"
+                exit 1
+              fi
+
+              if [ "$(params.emptyDefaultValue)" != "" ]; then
+                echo "Error: Expected index 5 to be '', got $(params.emptyDefaultValue)"
                 exit 1
               fi
