feat(RELEASE-1535): add option to use custom advisory id
Two new data fields are added:
* `.releaseNotes.live_id`
* `.releaseNotes.allow_custom_live_id`

The latter can only be set in RPA and defaults to false.
The former can be set in any of R, RP, RPA.

If `live_id` is set, but `allow_custom_live_id` is false,
the managed `create_advisory` task fails.

If `live_id` is set and `allow_custom_live_id` is true,
the internal `create_advisory_task` task will use this id
instead of requesting one from Errata Tool API.

Signed-off-by: Martin Malina <mmalina@redhat.com>

diff --git a/tasks/managed/create-advisory/create-advisory.yaml b/tasks/managed/create-advisory/create-advisory.yaml
--- a/tasks/managed/create-advisory/create-advisory.yaml
+++ b/tasks/managed/create-advisory/create-advisory.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: create-advisory
   labels:
-    app.kubernetes.io/version: "6.0.0"
+    app.kubernetes.io/version: "6.1.0"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -142,6 +142,14 @@ spec:
         # Extract the advisory key and signing configMap name from the data JSON file
         advisoryData=$(jq -c "$(params.jsonKey)" "$(params.dataDir)/$(params.dataPath)")
         configMapName=$(jq -er '.sign.configMapName' "$(params.dataDir)/$(params.dataPath)")
+
+        # Check custom advisory live id
+        advisoryLiveId=$(jq -r '.live_id' <<< "$advisoryData")
+        advisoryAllowCustomLiveId=$(jq -r '.allow_custom_live_id // false' <<< "$advisoryData")
+        if [ "$advisoryAllowCustomLiveId" != true ] && [ "$advisoryLiveId" != "null" ]; then
+          echo "Error: advisory live id is only allowed if allow_custom_live_id is set to true"
+          exit 1
+        fi
 
         # Validate type
         advisoryType=$(jq -r '.type' <<< "$advisoryData")
