feat(HACBS-1552): update upload sbom task
Adapt the task to support multiple images on the input.

Also, add a second step to run the upload_sbom script
for each sbom file.

Also, improve pyxisSecret description to mention
the requirement for key and cert.
Signed-off-by: Martin Malina <mmalina@redhat.com>

Also, update image used by the task to the one
with latest upload_sbom script updates.

Signed-off-by: Martin Malina <mmalina@redhat.com>

diff --git a/catalog/task/push-sbom-to-pyxis/0.1/push-sbom-to-pyxis.yaml b/catalog/task/push-sbom-to-pyxis/0.1/push-sbom-to-pyxis.yaml
--- a/catalog/task/push-sbom-to-pyxis/0.1/push-sbom-to-pyxis.yaml
+++ b/catalog/task/push-sbom-to-pyxis/0.1/push-sbom-to-pyxis.yaml
@@ -12,24 +12,90 @@ spec:
   description: >-
     Tekton task that extracts sbom from a pull spec and pushes it to Pyxis.
   params:
-    - name: imageURL
-      description: URL of the main binary image.
+    - name: imageURLs
+      description: Space separated list of binary image URLs that are used to obtain SBOMs via cosign
       type: string
+    - name: containerImageIDs
+      description: Space separated list of Pyxis image IDs
+      type: string
+    - name: pyxisSecret
+      type: string
+      description: |
+        The kubernetes secret to use to authenticate to Pyxis. It needs to contain two keys: key and cert
+    - name: server
+      type: string
+      description: The server type to use. Options are 'production' and 'stage'
+      default: production
   volumes:
     - name: workdir
       emptyDir: {}
   steps:
-    - name: download-sbom-for-image
-      # Image taken from https://github.com/sigstore/cosign
-      # and copied to Quay
+    - name: download-sbom-files
       image:
-        quay.io/redhat-appstudio/cosign:v1.13.1
-      args:
-        - download
-        - sbom
-        - --output-file
-        - /workdir/sbom-cyclonedx.json
-        - "$(params.imageURL)"
+        quay.io/hacbs-release/release-utils:5b1a1cd9fd68625cab5573ce62e0d87e6f93f341
       volumeMounts:
         - mountPath: /workdir
           name: workdir
+      script: |
+        #!/usr/bin/env sh
+        set -eux
+
+        IMAGEURLS=($(params.imageURLs))
+        IMAGEIDS=($(params.containerImageIDs))
+
+        if [ ${#IMAGEURLS[@]} != ${#IMAGEIDS[@]} ]; then
+          echo "ERROR: Lengths of imageURLs and containerImageIDs do not match"
+          exit 1
+        fi
+
+        mkdir /workdir/sboms
+        cd /workdir/sboms
+
+        for i in ${!IMAGEURLS[@]}; do
+          echo "Fetching sbom for image: ${IMAGEURLS[$i]}"
+          cosign download sbom --output-file ${IMAGEIDS[$i]}.json ${IMAGEURLS[$i]}
+        done
+
+    - name: push-sbom-files-to-pyxis
+      image:
+        quay.io/hacbs-release/release-utils:5b1a1cd9fd68625cab5573ce62e0d87e6f93f341
+      env:
+        - name: pyxisCert
+          valueFrom:
+            secretKeyRef:
+              name: $(params.pyxisSecret)
+              key: cert
+        - name: pyxisKey
+          valueFrom:
+            secretKeyRef:
+              name: $(params.pyxisSecret)
+              key: key
+      volumeMounts:
+        - mountPath: /workdir
+          name: workdir
+      script: |
+        #!/usr/bin/env sh
+        set -eu
+
+        if [[ "$(params.server)" == "production" ]]
+        then
+          export PYXIS_GRAPHQL_API="https://graphql-pyxis.api.redhat.com/"
+        elif [[ "$(params.server)" == "stage" ]]
+        then
+          export PYXIS_GRAPHQL_API="https://graphql-pyxis.preprod.api.redhat.com/"
+        else
+          echo "Invalid server parameter. Only 'production' and 'stage' are allowed."
+          exit 1
+        fi
+
+        export PYXIS_CERT_PATH=/workdir/crt
+        export PYXIS_KEY_PATH=/workdir/key
+        echo "${pyxisCert}" > $PYXIS_CERT_PATH
+        echo "${pyxisKey}" > $PYXIS_KEY_PATH
+
+        cd /workdir/sboms
+
+        for FILE in *.json; do
+          echo Uploading sbom to Pyxis: $FILE
+          upload_sbom --sbom-path $FILE
+        done
