feat(ISV-5658): add test for SBOM retry copy
Signed-off-by: Martin Jediny <jedinym@proton.me>

diff --git a/tasks/managed/upload-sbom-to-atlas/tests/test-upload-sbom-to-atlas-curl-fail.yaml b/tasks/managed/upload-sbom-to-atlas/tests/test-upload-sbom-to-atlas-curl-fail.yaml
--- a/tasks/managed/upload-sbom-to-atlas/tests/test-upload-sbom-to-atlas-curl-fail.yaml
+++ b/tasks/managed/upload-sbom-to-atlas/tests/test-upload-sbom-to-atlas-curl-fail.yaml
@@ -5,7 +5,9 @@ metadata:
   name: test-upload-sbom-to-atlas-curl-fail
 spec:
   description: |
-    Tests that failure in uploading SPDX SBOMs to Atlas should not fail the upload-sbom-to-atlas task.
+    Tests that failure in uploading SPDX SBOMs to Atlas should not fail the
+    upload-sbom-to-atlas task and the failed sbom is copied to the correct
+    directory for retrying.
   workspaces:
     - name: tests-workspace
   tasks:
@@ -70,17 +72,24 @@ spec:
           workspace: tests-workspace
       runAfter:
         - run-task
+      params:
+        - name: failedSbomDir
+          value: $(tasks.run-task.results.failedSbomDir)
       taskSpec:
         params:
           - name: sbomDir
             default: "sboms"
             description: Directory containing generated SBOM files.
             type: string
+          - name: failedSbomDir
         workspaces:
           - name: data
         steps:
           - name: check-result
             image: quay.io/konflux-ci/release-service-utils:3eb493f6b7923e04fbb01b44b24e5491a2bbd1ec
+            env:
+              - name: "FAILED_SBOM_DIR"
+                value: "$(params.failedSbomDir)"
             script: |
               #!/usr/bin/env bash
               set -eux
@@ -94,4 +103,14 @@ spec:
                 exit 1
               else
                 echo "TEST PASSED: Curl has been called 2 times"
+              fi
+
+              failedSbomDir="$(workspaces.data.path)/$FAILED_SBOM_DIR"
+
+              if [[ -f "$failedSbomDir/spdx_minimal_curl_fail_2_3.json.supported_version" ]]; then
+                echo "TEST PASSED: Failed SBOM was copied to retry directory."
+              else
+                echo "TEST FAILED: Failed SBOM not copied to retry directory."
+                ls -l "$failedSbomDir"
+                exit 1
               fi
