feat(RHTAPREL-624): update push-snapshot to publish source container
The new functionality is added to publish source containers to
a given target

  A new parameter exists called pushSourceContainer to enable/disable
  the source container push, the value is set to false by default

  A new tag `sourceTag = <prefix>-<integer timestamp>-source` is added
  for source container push

Signed-off-by: Happy Bhati <hbhati@redhat.com>

diff --git a/tasks/push-snapshot/push-snapshot.yaml b/tasks/push-snapshot/push-snapshot.yaml
--- a/tasks/push-snapshot/push-snapshot.yaml
+++ b/tasks/push-snapshot/push-snapshot.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: push-snapshot
   labels:
-    app.kubernetes.io/version: "1.0.1"
+    app.kubernetes.io/version: "1.1.0"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -20,6 +20,10 @@ spec:
       description: Path to the JSON string of the merged data to use in the data workspace
       type: string
       default: "data.json"
+    - name: pushSourceContainer
+      type: string
+      description: Push the source container to the mapped target
+      default: "false"
     - name: retries
       description: Retry copy N times.
       type: string
@@ -106,7 +110,16 @@ spec:
             --no-tags \
             --format '{{.Digest}}' \
             "docker://${repository}:${tag}" 2>/dev/null || true)
+          # Extract the SHA
+          if [[ "${containerImage}" == *"@sha256"* && $(echo "${containerImage}" | tr -cd ':' | wc -c) -eq 1 ]]
+          then
+            sha=$(echo "${containerImage}" | cut -d ':' -f 2)
+          else
+            sha=""
+          fi
+
           if [[ "$destination_digest" != "$source_digest" || -z "$destination_digest" ]]; then
+            # Push the container image
             push_image "${name}" "${containerImage}" "${repository}" "${tag}"
             if [[ $(jq -r ".images.addTimestampTag" "${DATA_FILE}") == "true" ]] ; then # Default to false
               timestamp=$(date +"%Y-%m-%dT%H:%M:%SZ" | sed 's/:/-/g')
@@ -122,14 +135,24 @@ spec:
               fi
             fi
             if [[ $(jq -r ".images.addSourceShaTag" "${DATA_FILE}") != "false" ]] ; then # Default to true
-              if [[ "${containerImage}" == *"@sha256"* && $(echo "${containerImage}" | tr -cd ':' | wc -c) -eq 1 ]]
-              then
-                sha=$(echo "${containerImage}" | cut -d ':' -f 2)
+              if [ -n "$sha" ]; then
                 push_image "${name}" "${containerImage}" "${repository}" "${sha}"
               else
                 printf 'Asked to create source sha based tag, but no sha found in %s\n' "${containerImage}"
                 exit 1
               fi
+            fi
+            # Push the associated source container using the common tag
+            if [[ "$(params.pushSourceContainer)" == "true" ]] ; then # Default to false
+              # Calculate the source container image based on the provided container image
+              sourceContainer="${containerImage%@sha256:*}@sha256:${sha}.src"
+              # Check if the source container exists
+              if ! skopeo inspect --no-tags "docker://${sourceContainer}" &>/dev/null; then
+                echo "Error: Source container ${sourceContainer} not found!"
+                exit 1
+              fi              
+              sourceTag="${prefixedTag}-source"
+              push_image "${name}" "${sourceContainer}" "${repository}" "${sourceTag}"
             fi
           else
             printf '* Component push skipped (source digest exists at destination): %s (%s)\n' \
