feat(RELEASE-207): validate advisory type
The advisory type has to be one of RHSA, RHBA or RHEA.

Signed-off-by: David Moreno García <damoreno@redhat.com>

diff --git a/tasks/create-advisory/create-advisory.yaml b/tasks/create-advisory/create-advisory.yaml
--- a/tasks/create-advisory/create-advisory.yaml
+++ b/tasks/create-advisory/create-advisory.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: create-advisory
   labels:
-    app.kubernetes.io/version: "4.1.0"
+    app.kubernetes.io/version: "4.2.0"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -63,6 +63,13 @@ spec:
         # Extract the advisory key and signing configMap name from the data JSON file
         advisoryData=$(jq -c "$(params.jsonKey)" $(workspaces.data.path)/$(params.dataPath))
         configMapName=$(jq -er '.sign.configMapName' $(workspaces.data.path)/$(params.dataPath))
+
+        # Validate type
+        advisoryType=$(jq -r ".type" <<< "$advisoryData")
+        if ! [[ "$advisoryType" =~ ^(RHSA|RHBA|RHEA)$ ]]; then
+            echo "Error: advisory type must be one of RHSA, RHBA or RHEA"
+            exit 1
+        fi
 
         pipelinerun_label="internal-services.appstudio.openshift.io/pipelinerun-uid"
 
