fix(RHTAPBUGS-919): run sbom uploads in parallel
Up to 4 sbom uploads will run in parallel. This will improve
the performance of the task.

Signed-off-by: Martin Malina <mmalina@redhat.com>

diff --git a/tasks/push-sbom-to-pyxis/push-sbom-to-pyxis.yaml b/tasks/push-sbom-to-pyxis/push-sbom-to-pyxis.yaml
--- a/tasks/push-sbom-to-pyxis/push-sbom-to-pyxis.yaml
+++ b/tasks/push-sbom-to-pyxis/push-sbom-to-pyxis.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: push-sbom-to-pyxis
   labels:
-    app.kubernetes.io/version: "0.4.0"
+    app.kubernetes.io/version: "0.5.0"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -27,6 +27,10 @@ spec:
       type: string
       description: The server type to use. Options are 'production' and 'stage'
       default: production
+    - name: concurrentLimit
+      type: string
+      description: The maximum number of images to be processed at once
+      default: 4
   workspaces:
     - name: data
       description: The workspace where the snapshot spec json file resides
@@ -65,6 +69,12 @@ spec:
           echo "Fetching sbom for image: ${IMAGEURLS[$i]}"
           cosign download sbom --output-file "${IMAGEIDS[$i]}.json" "${IMAGEURLS[$i]}"
         done
+
+        SBOM_COUNT=$(ls *.json | wc -l )
+        if [ $SBOM_COUNT != ${#IMAGEURLS[@]} ]; then
+          echo "ERROR: Expected to fetch sbom for ${#IMAGEURLS[@]} images, but only $SBOM_COUNT were saved"
+          exit 1
+        fi
 
     - name: push-sbom-files-to-pyxis
       image:
@@ -105,7 +115,47 @@ spec:
 
         cd /workdir/sboms
 
+        N=$(params.concurrentLimit)  # The maximum number of images to be processed at once
+        declare -a jobs=()
+        declare -a files=()
+        total=$(ls *.json | wc -l )
+        count=0
+        success=true
+        echo "Starting sbom upload for $total files in total. " \
+          "Up to $N files will be uploaded at once..."
+
         for FILE in *.json; do
           echo Uploading sbom to Pyxis: $FILE
-          upload_sbom --retry --sbom-path $FILE
+          upload_sbom --retry --sbom-path $FILE > ${FILE}.out 2>&1 &
+
+          jobs+=($!)  # Save the background process ID
+          files+=($FILE)
+          ((++count))
+
+          if [ $((count%N)) -eq 0 -o $((count)) -eq $total ]; then
+            echo Waiting for the current batch of background processes to finish
+            for i in "${!jobs[@]}"; do
+              if ! wait ${jobs[i]}; then
+                echo "Error: upload of ${files[i]} failed"
+                success=false
+              fi
+            done
+
+            echo
+            echo Printing outputs for current upload_sbom script runs
+            for FILE in ${files[@]}; do
+              echo "=== $FILE ==="
+              cat "${FILE}.out"
+              echo
+            done
+
+            if [ $success != "true" ]; then
+              echo ERROR: At least one upload in the last batch failed
+              exit 1
+            fi
+
+            # Reset job and files arrays for the next batch
+            jobs=()
+            files=()
+          fi
         done
