refactor: update existing internal-services manager prs
This commit changes the task used in the internal-services final
pipeline to update an existing PR to the stable branch if one exists
instead of always opening a new one from a new branch. This helps
prevent an endless number of branches/prs being created if the PRs
aren't timely merged.

Signed-off-by: Johnny Bieren <jbieren@redhat.com>

diff --git a/tasks/tenant/update-manager-image-in-git/update-manager-image-in-git.yaml b/tasks/tenant/update-manager-image-in-git/update-manager-image-in-git.yaml
--- a/tasks/tenant/update-manager-image-in-git/update-manager-image-in-git.yaml
+++ b/tasks/tenant/update-manager-image-in-git/update-manager-image-in-git.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: update-manager-image-in-git
   labels:
-    app.kubernetes.io/version: "0.1.0"
+    app.kubernetes.io/version: "0.1.1"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: "release, tenant"
@@ -72,7 +72,7 @@ spec:
 
           BRANCH=$(params.repoBranch)
           if [ "$(params.mode)" = "pr" ] ; then
-              BRANCH="manager-update-$(date +%s)" 
+              BRANCH="automated-manager-update"
               git checkout -b "$BRANCH"
           fi
 
@@ -86,5 +86,7 @@ spec:
           git push -f origin "$BRANCH"
 
           if [ "$(params.mode)" = "pr" ] ; then
-              gh pr create --base "$(params.repoBranch)" --head "$BRANCH" --title "$TITLE" --body ""
+              # This command will fail if there is already an open PR. In this case, the push before this
+              # will update the PR so it is okay if this fails
+              gh pr create --base "$(params.repoBranch)" --head "$BRANCH" --title "$TITLE" --body "" || true
           fi
